### ISSUE TITLE
Animations not working with custom placeholders.

### ISSUE THREAD

**Issue by mskasal** [buildo/react-placeholder#34]
showLoadingAnimation prop not working with custom placeholders.

```javascript
render() {
   <ReactPlaceholder showLoadingAnimation ready={ready} customPlaceholder={<TextRow />}>
           <div className={bodyClasses}>
             {children}
           </div>
    </ReactPlaceholder>
}
```

**Comment by DaPo** [comment]
Hi,

Same issue here:
```<ReactPlaceholder
        customPlaceholder={awesomePlaceholder}
        showLoadingAnimation
        ready={false}
      >
        <div>test</div>
      </ReactPlaceholder>```

`reactPlaceholder.css` is called in my Component but I don't see any animation.

Did I miss something?

Thank you!

**Comment by FrancescoCioria** [comment]
Hi @mskasal and @DaPo, sorry for the late answer!

Talking about the issue, I'm not sure fully understand it: when you say "custom placeholders" are you referring to components completely custom or built with `react-placeholder`'s exported components?

If it's the second case we may be able to find a fix, but for the first one I don't see any possible way as it's your duty to pass the right `className` to your completely custom component

**Comment by DaPo** [comment]
Hi @FrancescoCioria,

It was indeed with `react-placeholder`'s exported components, like this:

```JS
const awesomePlaceholder = (
    <div>
       <RectShape
         color="#EEEEEE"
         style={{ flexShrink: 0, width: 184, height: 270 }}
       />
       <TextBlock
         rows={7}
         color="#EEEEEE"
       />
     </div>
 );
 ```

 Then: 
 ```JS
return (
   <ReactPlaceholder
     customPlaceholder={awesomePlaceholder}
     ready={false}
     showLoadingAnimation
   >
     <div></div>
   </ReactPlaceholder>
);
```

Please don't mind the empty DIV tag that will have my loaded component, it's just a test case here.

So as you can see, I tried to make the `showLoadingAnimation` working but it seems like it won't load the className in the DOM if we have custom markup.

So the workaround until the bug is fixed: I added a `className="show-loading-animation"` to my wrapper in my const and copy/paste your keyframes in one of my CSS files.

That's it!

I hope my answer is clear, my english is pretty bad.

Thank you for your job and have a nice day.

**Comment by FrancescoCioria** [comment]
Thank you @DaPo , perfectly clear :)

I'll review the open PR to see if it's a suitable fix

**Comment by DaPo** [comment]
@FrancescoCioria thank you very much!

See you.
