### ISSUE TITLE
[Typings] Can't assign Element to customPlaceholder

### ISSUE THREAD

**Issue by pgvlas** [buildo/react-placeholder#75]
When I try to pass Element to customPlaceholder prop it returns following type error:

`Type 'element' is not assignable to type 'undefined'.`

```
    const awesomePlaceholder = (
      <div>
        <RectShape color="blue" style={{width: 30, height: 80}}/>
        <TextBlock rows={7} color="yellow"/>
      </div>
    );

    return (
      <ReactPlaceholder
        type="rect"
        showLoadingAnimation={true}
        customPlaceholder={awesomePlaceholder}
        ready={!isLoading}
      >
    )
```

Also, type prop is required but we shouldn't pass it using `customPlaceholder`. Is it something to fix or I'm doing something wrong?

**Comment by gabro** [comment]
The error is a bit confusing, but essentially you need to skip `type` and `showLoadingAnimation`. Since you're passing a custom placeholder, those two props don't apply anymore.

This is specified as a union type in the [props definitions](https://github.com/buildo/react-placeholder/blob/master/src/ReactPlaceholder.tsx#L17-L34).

Essentially this should typecheck fine:

```jsx
<ReactPlaceholder
  customPlaceholder={awesomePlaceholder}
  ready={!isLoading}
/>
```
